baseURL = "https://indiecoder.vercel.app/"
languageCode = "en-us"
title = "IndieCoder"
theme="archie"
copyright = "Hein Thant"
# Code Highlight
pygmentsstyle = "native" # github-dark, 
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "indiecoder"

defaultContentLanguage = 'en'
[languages]
  [languages.mm]
    languageName = 'MM'
    weight = 2
  [languages.en]
    languageName = 'EN'
    weight = 1

[pagination]
  pagerSize = 3

[params]
	mode="dark" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Just writing down my journey and things I've learned. Occasionally sound like I know what I'm doing."
	mathjax = false # enable MathJax support
	katex = false # enable KaTeX support

  [params.author]
    email = 'hthant00chk@gmail.com'
    name = 'Hein Thant'

# Social Tags
[[params.social]]
name = "GitHub"
icon = "simple:github"
url = "https://github.com/indiecodermm/"

[[params.social]]
name = "BlueSky"
icon = "simple:bluesky"
url = "https://bsky.app/profile/heinthantoo.bsky.social"

[[params.social]]
name = "LinkedIn"
icon = "simple:linkedin"
url = "https://www.linkedin.com/in/hthantoo/"

# Main menu Items

# [[menu.main]]
# name = "Home"
# url = "/"
# weight = 1

[[menu.main]]
name = "Blogs"
url = "/blogs"
weight = 1

[[menu.main]]
name = "Library"
url = "/library"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

