baseURL = "https://indiecodermm.github.io/"
languageCode = "en-us"
title = "IndieCoder"
theme="archie"
copyright = "© Hein Thant"
# Code Highlight
pygmentsstyle = "github-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "heinthant"

paginate=3 # articles per page  

[params]
	mode="dark" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Just a blog for a coder's thoughts, experiences and everything in between."
	mathjax = false # enable MathJax support
	katex = false # enable KaTeX support

# Social Tags

[[params.social]]
name = "GitHub"
icon = "simple:github"
url = "https://github.com/indiecodermm/"

[[params.social]]
name = "BlueSky"
icon = "simple:bluesky"
url = "https://twitter.com/hthantoo/"

[[params.social]]
name = "LinkedIn"
icon = "simple:linkedin"
url = "https://www.linkedin.com/in/hthantoo/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blogs"
url = "/blogs"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
